version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis-for-campusx
    ports:
      - "6379:6379"
    restart: unless-stopped

  chroma:
    build:
      context: ./chroma
      dockerfile: Dockerfile  # This must be the Dockerfile you shared above
    container_name: chroma-campux
    ports:
      - "8001:8001"
    volumes:
      - chroma-data:/chroma/chroma
    restart: unless-stopped

  campusx-api-server:
    build: .
    container_name: campusx-api-server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CHROMA_URL=http://chroma:8001
    depends_on:
      - redis
      - chroma
    command: ["node", "index.js"]

  cmo-agent-server:
    build: .
    container_name: cmo-agent-server
    environment:
      - REDIS_URL=redis://redis:6379
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CHROMA_URL=http://chroma:8001
    depends_on:
      - redis
      - chroma
    command: ["node", "agentsEntry/cmoAgentEntry.js"]

  cto-agent-server:
    build: .
    container_name: cto-agent-server
    environment:
      - REDIS_URL=redis://redis:6379
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CHROMA_URL=http://chroma:8001
    depends_on:
      - redis
      - chroma
    command: ["node", "agentsEntry/ctoAgentEntry.js"]

  cfo-agent-server:
    build: .
    container_name: cfo-agent-server
    environment:
      - REDIS_URL=redis://redis:6379
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CHROMA_URL=http://chroma:8001
    depends_on:
      - redis
      - chroma
    command: ["node", "agentsEntry/cfoAgentEntry.js"]

  ceo-agent-server:
    build: .
    container_name: ceo-agent-server
    environment:
      - REDIS_URL=redis://redis:6379
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CHROMA_URL=http://chroma:8001
    depends_on:
      - redis
      - chroma
    command: ["node", "agentsEntry/ceoAgentEntry.js"]

volumes:
  chroma-data: